pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker_hub')
	//SSH_CREDENTIALS = credentials('ssh_connect')
    }

    stages {
        stage('Build') {
            steps {
                script {
		    echo 'Test begin'
                    // Build the Docker image
                    sh 'docker build -t genesisalpha456/hello ./helloWorld/'
		    echo 'This where the change happend'
                }
            }
        }
        stage('Push') {
            steps {
                script {
			echo 'Woking on pushing the image to hub'
                    // Push the Docker image to Docker Hub
                    docker.withRegistry('', 'docker_hub') {
                        docker.image('genesisalpha456/hello').push('latest')
                    }
                }
            }
        }
	stage('Connect_ssh') {
	    steps {
	        script {
	            sshagent(credentials: ['ssh_connect']) {
	                sh 'hostname -I'
	                sh 'ssh -o StrictHostKeyChecking=no root@104.131.183.80 "ls && docker pull genesisalpha456/hello:latest && docker run -d -p 8765:80 genesisalpha456/hello:latest"'
	                echo 'Task completed!'
	            }
	        }
	    }
	}
    }
}

