pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker_hub')
    }

    stages {
        stage('Build') {
            steps {
                script {
		    echo 'Test begin'
                    // Build the Docker image
                    sh 'docker build -t genesisalpha456/hello ./helloWorld/'
		    echo 'This where the change happend'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push the Docker image to Docker Hub
                    docker.withRegistry('', 'docker_hub') {
                        docker.image('genesisalpha456/hello').push('latest')
                    }
                }
            }
        }
	stage('Connect_ssh'){
	    steps {
		script {
			// Connect to the other instance using ssh
			sh 'ssh -T root 138.197.116.169'
			echo 'Connected using ssh'
			sh 'docker pull genesisalpha456/hello:latest'
			sh 'docker run --name hello_world -d genesisalpha456/hello:latest'
			def psOutput = sh(script: 'docker ps', returnStdout: true).trim()
                        println("Docker PS Output:\n${psOutput}")
		   }
		}
	}
    }
}

