pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker_hub')
    }

    stages {
        stage('Build') {
            steps {
                script {
		    echo 'Test begin'
                    // Build the Docker image
                    docker build -t my-docker-image .
		    echo 'This where the change happend'
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    // Push the Docker image to Docker Hub
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials-id') {
                        docker.image('my-docker-image').push('latest')
                    }
                }
            }
        }
    }
}

